name: CI

on:
  push:
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: AbsaOSS/k3d-action@v2
        name: "Create a kubernetes cluster"
        with:
          cluster-name: "temporary-test-cluster"
          args: >-
            -p "5008:30008@loadbalancer"
            --agents 1

      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install required dependencies
        run: npm ci

      - name: Run e2e tests
        run: npm run e2e-on-pre-existing-cluster
